### PR TITLE
fixed #43 #44 #47

### LINKED ISSUE #43: Eagle faint trigger does not multiply hp or attack
Eagle should multiply the spawned pet hp and attack by its level. (quick example i could find: [https://youtu.be/zZR8Offnrp8?t=598](https://youtu.be/zZR8Offnrp8?t=598) )

```
def test_eagle_ability(self):
  state = np.random.RandomState(seed=4).get_state()

  # seed for Snake 6/6
  pet = Pet("eagle", seed_state=state)
  pet.level = 3
  player = Player(shop=Shop(["sleeping-pill"]), team=Team([pet]))
  player.buy_food(0, 0)        

  # should spawn Snake Lvl3 18/18 since Eagle was lvl 3
  print(player.team)
  self.assertEqual(player.team[0].level, 3)
  self.assertEqual(player.team[0].attack, 18)
  self.assertEqual(player.team[0].health, 18)
```

### PR DESCRIPTION
**Pull request by jimkaal**
Fixed issue #43 

Added a statsModifier to the eagles effect that will scale the attack and health of the summoned pet.
Also included a unittest to confirm the changes.

### CODE REVIEW

**Comment by jimkaal** [comment]
Also fixed #44 
The mult should always do -1

**Comment by jimkaal** [comment]
#47 
Also implemented coconut shield and weak.
Added unittests to check for both DealDamage ability and normal attacks.

**Comment by jimkaal** [comment]
When pilling a hedgehog for example, damage was not triggering hurt abilities.
Also added a unittest to test all the hurt abilities and make sure blowfish does not throw errors for not having an enemy team present.

**Comment by alexdriedger** [comment]
I like all the tests. Just need @manny405 to approve running the workflow

**Comment by manny405** [comment]
Approved. Past month has been too busy for me. Finished PhD thesis, started new job, moving states... Will get back to things starting next month. Thanks for the help!

**Review by manny405 — APPROVED** [review]

**Pull request merged**
