### PR TITLE
Update stats of animals

### PR DESCRIPTION
**Pull request by andreped**
Since sapai had its last update, SAP have had a patch update which updated the stats of a lot of the pets in the standard pack.

I have therefore updated these to match the current state of SAP.

To get the correct values I used this page:
https://superautopets.fandom.com/wiki/Pets

I have not added any new updates to the change notes at the top of the script. If you want me to, give me a suggestion on what to write. Perhaps "Updated the stats of all animals in the standard pack to match patch update X of SAP"?

### CODE REVIEW

**Comment by manny405** [comment]
Tests will have to be updated with updated pet stats. Will get back to this soon.

**Comment by andreped** [comment]
> Will get back to this soon.

Great! Looking forward to collaborating on the project :)

I can update the tests later today and request you to review.

**Comment by andreped** [comment]
I just looked at the tests and I am a little unsure where to actually update. I would probably need to spend more time on the tests to see where I would need to change. Don't really have time for that this week.

But when you get back to this, I guess you will take a look. You can make a commit to my branch and we could merge it when it is ready. No rush!

**Comment by manny405** [comment]
Pet changes in this PR are now reflected in main. There are some more changes I will have to make including more extensive test cases. I have a list made.

**Comment by andreped** [comment]
@manny405 OK, no worries. Would be great if you could make a release (v0.1.0) including the generated binary wheel:
https://github.com/manny405/sapai/actions/runs/2935827980

Next time I would've preferred if the edits were made in the same branch as I was working in such that the edits I did would have been part of the PR, especially as it seems that the same edits were made, just adding some other stuff.

**Pull request closed without merging**
